#!/bin/bash
OUTPUT_FILE="src/data_translations.vala"

{
  echo "// This file is automatically generated. Do not edit."
  echo "namespace DataTranslations {"
  echo "    // These strings are extracted for translation"
  echo "    public void initialize_translations() {"

  # Extract descriptions from JSON
  jq -r '.[].description' src/assets/fonts.json | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | while read -r line; do
    [ -z "$line" ] && continue
    ESCAPED=$(echo "$line" | sed 's/"/\\"/g')
    echo "        _(\"$ESCAPED\");"
  done

  # Extract values from licences (skip section headers)
  grep "=" src/assets/licences | grep -v "^\[" | cut -d= -f2- | while read -r line; do
    ESCAPED=$(echo "$line" | sed 's/"/\\"/g')
    echo "        _(\"$ESCAPED\");"
  done

  echo "    }"
  echo "}"
} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
