#!/bin/bash

OUTPUT_FILE="src/data_translations.js"

echo "// This file is automatically generated. Do not edit." > "$OUTPUT_FILE"
echo "import { gettext as _ } from 'gettext';" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Extract descriptions from data/fonts
grep "^description=" data/fonts | cut -d= -f2- | while read -r line; do
    # Escape single quotes
    ESCAPED_LINE=$(echo "$line" | sed "s/'/\\\\'/g")
    echo "_('$ESCAPED_LINE');" >> "$OUTPUT_FILE"
done

# Extract descriptions from data/licences (values only, skipping [header])
# Format is Key=Value
grep "=" data/licences | grep -v "^\[" | cut -d= -f2- | while read -r line; do
    ESCAPED_LINE=$(echo "$line" | sed "s/'/\\\\'/g")
    echo "_('$ESCAPED_LINE');" >> "$OUTPUT_FILE"
done

echo "Generated $OUTPUT_FILE"
